version: '3'
services:
  backend:
    build: api/.
    ports:
      - "5001:5001"
  frontend:
    build: frontend/.
    ports:
      - "5000:80"
  db:
    image: mongo
    volumes:
        - ${HOME}/data/db:/data/db
    ports:
      - "27017:27017"
